### ISSUE TITLE
Sitemap Index

### ISSUE THREAD

**Issue by sajumani** [pawelantczak/php-sitemap-generator#3]
Hi,

Sitemap Index not getting generated , could you please check this??

**Comment by pawelantczak** [comment]
Check what exactly?

**Comment by sajumani** [comment]
am expecting to have sitemap-index.xml should be create after all sitemap generated...

For more info... this sdk has option   https://github.com/o/sitemap-php  but they don't have gzip ...so i combined both and created one for me...

Thanks,
